### PR TITLE
Added SpriteImageRenderer

### PR DESCRIPTION
**Pull request by Gopal-moyya**

### CODE REVIEW

**Comment by jfboeve** [comment]
Hi @Gopal-moyya,

That looks like a fun component! I do however have a few notes that need to be adjusted.

1. Please change this PR to dev according to [Contributing guidelines](https://github.com/rdkcentral/Lightning-ui#contributing)
2. Replace the emits with signals. f.e. this.emit('spriteLoopCycleEnd') to this.signal('onLoopCycleEnded').
3. Add getters to accompany the setters.
4. Remove 'Ex:' from the code blocks in the doc files.

**Comment by jfboeve** [comment]
@Gopal-moyya Thanks for your contribution! I plan to release a new version at the end of the week!

**Comment by jfboeve** [comment]
@Gopal-moyya can you sign the CLA

**Comment by Gopal-moyya** [comment]
> @Gopal-moyya can you sign the CLA

@jfboeve completed.

**Pull request merged**
